version: 0.1
default:
  build:
    parameters:
      cached: 'true'
      parallel: 'true'
  deploy:
    parameters:
      stack_name: {{StackName}}
      capabilities: CAPABILITY_IAM
      image_repositories: []