version: 0.1
default:
  build:
    parameters:
      cached: 'true'
      parallel: 'true'
  deploy:
    parameters:
      stack_name: the-stack
      s3_bucket: dev
      capabilities: CAPABILITY_IAM
      image_repositories: []