name: prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/shared-lint.yaml
    secrets: inherit

  unit-tests:
    name: Unit Tests
    uses: ./.github/workflows/shared-unit-tests.yaml
    secrets: inherit

  deploy-resources:
    name: Deploy SAM Resources
    needs: [lint, unit-tests]
    uses: ./.github/workflows/shared-deploy.yaml
    with:
      ENVIRONMENT: prod
      AWS_REGION: us-east-1
      PIPELINE_EXECUTION_ROLE: prod
      CLOUDFORMATION_EXECUTION_ROLE: prod
      ARTIFACTS_BUCKET_NAME: prod
      STACK_NAME: the-stack
    secrets: inherit

  test-api:
    name: Test API
    needs: [deploy-resources]
    uses: ./.github/workflows/shared-test-api.yaml
    with:
      ENVIRONMENT: prod
      AWS_REGION: us-east-1
      PIPELINE_EXECUTION_ROLE: prod
      STACK_NAME: the-stack
    secrets: inherit
