name: qa

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/shared-lint.yaml
    secrets: inherit

  unit-tests:
    name: Unit Tests
    uses: ./.github/workflows/shared-unit-tests.yaml
    secrets: inherit

  deploy-resources:
    name: Deploy SAM Resources
    needs: [lint, unit-tests]
    uses: ./.github/workflows/shared-deploy.yaml
    with:
      ENVIRONMENT: qa
      AWS_REGION: us-east-2
      PIPELINE_EXECUTION_ROLE: d
      CLOUDFORMATION_EXECUTION_ROLE: e
      ARTIFACTS_BUCKET_NAME: f
      STACK_NAME: my-branc-new-stack
    secrets: inherit

  test-api:
    name: Test API
    needs: [deploy-resources]
    uses: ./.github/workflows/shared-test-api.yaml
    with:
      ENVIRONMENT : qa
      AWS_REGION: us-east-2
      PIPELINE_EXECUTION_ROLE: d
      STACK_NAME: my-branc-new-stack
    secrets: inherit
