name: Unit Tests & Code Coverage

on:
  workflow_call:

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "**/index.tests.js"
      - name: Run Unit Tests & Code Coverage
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          npm ci
          npm run coverage