name: Build and Deploy artifacts for a given input environment

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      STACK_NAME:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    name: Build and Deploy SAM Application
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - uses: actions/checkout@v3
      - name: Replace Variables in samconfig
        run: |
          npm i -g replace-in-files-cli
          replace-in-files --string={{Environment}} --replacement=${{ inputs.ENVIRONMENT }} ./samconfig.ci.toml
          replace-in-files --string={{StackName}} --replacement= ${{ inputs.STACK_NAME }} ./samconfig.ci.toml
      - run: |
          npm install -g esbuild
          npm ci
          sam build
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.PIPELINE_EXECUTION_ROLE }}
          role-session-name: packaging
          role-duration-seconds: 3600
          role-skip-session-tagging: true
      - name: Deploy
        run: |
          sam deploy \
          --s3-bucket ${{ secrets.ARTIFACTS_BUCKET_NAME }} \
          --no-fail-on-empty-changeset \
          --role-arn ${{ secrets.CLOUDFORMATION_EXECUTION_ROLE }}
